import Testing
import RhoeMarkdownKit

@Suite("Sprint 7: Writer Protocol + LaTeX Writer")
struct Sprint7ConformanceTests {

    // MARK: - 7.1 Headings

    @Test("Headings render as section commands")
    func headings() async {
        let md = "# Chapter\n\n## Section\n\n### Subsection"
        let result = await RhoeMarkdownKit.parse(md)
        let latex = RhoeMarkdownKit.renderLaTeX(result.document, configuration: .flat)
        #expect(latex.contains("\\section{Chapter}"))
        #expect(latex.contains("\\subsection{Section}"))
        #expect(latex.contains("\\subsubsection{Subsection}"))
    }

    // MARK: - 7.2 Inline Formatting

    @Test("Bold and italic render correctly")
    func inlineFormatting() async {
        let md = "This is **bold** and *italic* text."
        let latex = await RhoeMarkdownKit.toLaTeX(md)
        #expect(latex.contains("\\textbf{bold}"))
        #expect(latex.contains("\\textit{italic}"))
    }

    @Test("Inline code renders as texttt")
    func inlineCode() async {
        let md = "Use `printf()` here."
        let latex = await RhoeMarkdownKit.toLaTeX(md)
        #expect(latex.contains("\\texttt{printf()}"))
    }

    // MARK: - 7.3 Math Pass-Through

    @Test("Inline math passes through as dollar signs")
    func mathInline() async {
        let md = "The equation $E = mc^2$ is famous."
        let latex = await RhoeMarkdownKit.toLaTeX(md)
        #expect(latex.contains("$E = mc^2$"))
    }

    @Test("Display math renders as bracket delimiters")
    func mathDisplay() async {
        let md = "$$\\int_0^1 x^2 dx$$"
        let latex = await RhoeMarkdownKit.toLaTeX(md)
        #expect(latex.contains("\\[\\int_0^1 x^2 dx\\]"))
    }

    // MARK: - 7.4 Lists

    @Test("Unordered list renders as itemize")
    func unorderedList() async {
        let md = "- First\n- Second\n- Third"
        let latex = await RhoeMarkdownKit.toLaTeX(md)
        #expect(latex.contains("\\begin{itemize}"))
        #expect(latex.contains("\\item"))
        #expect(latex.contains("\\end{itemize}"))
    }

    @Test("Ordered list renders as enumerate")
    func orderedList() async {
        let md = "1. First\n2. Second\n3. Third"
        let latex = await RhoeMarkdownKit.toLaTeX(md)
        #expect(latex.contains("\\begin{enumerate}"))
        #expect(latex.contains("\\item"))
        #expect(latex.contains("\\end{enumerate}"))
    }

    // MARK: - 7.5 Code Blocks

    @Test("Fenced code block renders as lstlisting")
    func codeBlock() async {
        let md = "```python\nprint('hello')\n```"
        let result = await RhoeMarkdownKit.parse(md)
        let latex = RhoeMarkdownKit.renderLaTeX(result.document, configuration: .flat)
        #expect(latex.contains("\\begin{lstlisting}[language=python]"))
        #expect(latex.contains("print('hello')"))
        #expect(latex.contains("\\end{lstlisting}"))
    }

    // MARK: - 7.6 Tables

    @Test("Table renders as tabular")
    func table() async {
        let md = "| A | B |\n|---|---|\n| 1 | 2 |"
        let latex = await RhoeMarkdownKit.toLaTeX(md)
        #expect(latex.contains("\\begin{tabular}"))
        #expect(latex.contains("\\end{tabular}"))
    }

    // MARK: - 7.7 Block Quotes

    @Test("Block quote renders as quote environment")
    func blockQuote() async {
        let md = "> This is a quote."
        let latex = await RhoeMarkdownKit.toLaTeX(md)
        #expect(latex.contains("\\begin{quote}"))
        #expect(latex.contains("\\end{quote}"))
    }

    // MARK: - 7.8 Preamble

    @Test("Full document preamble generated by default")
    func preamble() async {
        let md = "# Hello\n\nWorld."
        let latex = await RhoeMarkdownKit.toLaTeX(md)
        #expect(latex.contains("\\documentclass{article}"))
        #expect(latex.contains("\\begin{document}"))
        #expect(latex.contains("\\end{document}"))
        #expect(latex.contains("\\usepackage{amsmath}"))
    }

    @Test("Fragment mode omits preamble")
    func fragmentMode() async {
        let config = RhoeMarkdownKit.LaTeXConfiguration(generatePreamble: false, astNearEmission: false)
        let result = await RhoeMarkdownKit.parse("# Hello\n\nWorld.")
        let latex = RhoeMarkdownKit.renderLaTeX(result.document, configuration: config)
        #expect(!latex.contains("\\documentclass"))
        #expect(!latex.contains("\\begin{document}"))
        #expect(latex.contains("\\section{Hello}"))
    }

    @Test("Title from frontmatter generates maketitle")
    func frontmatterTitle() async {
        let md = """
        ---
        title: My Paper
        author: Thor Fuchs
        date: "2026"
        ---

        # Introduction

        Hello.
        """
        let latex = await RhoeMarkdownKit.toLaTeX(md)
        #expect(latex.contains("\\title{My Paper}"))
        #expect(latex.contains("\\author{Thor Fuchs}"))
        #expect(latex.contains("\\maketitle"))
    }

    // MARK: - 7.9 LaTeX Escaping

    @Test("Special characters escaped in text")
    func latexEscaping() async {
        let md = "Cost is 100% of $50 & tax #1."
        let latex = await RhoeMarkdownKit.toLaTeX(md)
        #expect(latex.contains("100\\%"))
        #expect(latex.contains("\\$50"))
        #expect(latex.contains("\\&"))
        #expect(latex.contains("\\#1"))
    }

    // MARK: - 7.10 Citations in LaTeX

    @Test("Resolved citation renders as cite command")
    func citationLaTeX() async {
        let md = """
        ---
        references:
          - id: smith2024
            author: Smith
            title: Study
            year: "2024"
        ---

        See [@smith2024].
        """
        let latex = await RhoeMarkdownKit.toLaTeX(md)
        #expect(latex.contains("\\cite{smith2024}"))
    }

    // MARK: - 7.11 Cross-References in LaTeX

    @Test("Cross-reference renders as ref command")
    func crossRefLaTeX() async {
        let md = "See @fig-chart."
        let latex = await RhoeMarkdownKit.toLaTeX(md)
        #expect(latex.contains("\\ref{"))
    }

    // MARK: - 7.12 Theorem Environments

    @Test("Theorem div renders as theorem environment")
    func theoremLaTeX() async {
        let md = "::: {.theorem}\nAll primes > 2 are odd.\n:::"
        let latex = await RhoeMarkdownKit.toLaTeX(md)
        #expect(latex.contains("\\begin{theorem}"))
        #expect(latex.contains("\\end{theorem}"))
    }
}
