import Testing
import RhoeMarkdownKit

@Suite("Sprint 8: Typst + DOCX Writers")
struct Sprint8ConformanceTests {

    // MARK: - 8.1 Typst Headings

    @Test("Typst headings use equals signs")
    func typstHeadings() async {
        let md = "# Chapter\n\n## Section\n\n### Subsection"
        let result = await RhoeMarkdownKit.parse(md)
        let typst = RhoeMarkdownKit.renderTypst(result.document, configuration: .flat)
        #expect(typst.contains("= Chapter"))
        #expect(typst.contains("== Section"))
        #expect(typst.contains("=== Subsection"))
    }

    // MARK: - 8.2 Typst Inline Formatting

    @Test("Typst bold and italic")
    func typstInlineFormatting() async {
        let md = "This is **bold** and *italic* text."
        let typst = await RhoeMarkdownKit.toTypst(md)
        #expect(typst.contains("*bold*"))
        #expect(typst.contains("_italic_"))
    }

    @Test("Typst inline code")
    func typstInlineCode() async {
        let md = "Use `printf()` here."
        let typst = await RhoeMarkdownKit.toTypst(md)
        #expect(typst.contains("`printf()`"))
    }

    // MARK: - 8.3 Typst Math

    @Test("Typst math pass-through")
    func typstMath() async {
        let md = "The equation $E = mc^2$ is famous."
        let typst = await RhoeMarkdownKit.toTypst(md)
        #expect(typst.contains("$E = mc^2$"))
    }

    // MARK: - 8.4 Typst Lists

    @Test("Typst unordered list uses #rhoe-list in AST-near mode")
    func typstUnorderedList() async {
        let md = "- First\n- Second"
        let typst = await RhoeMarkdownKit.toTypst(md)
        #expect(typst.contains("#rhoe-list"))
        #expect(typst.contains("First"))
        #expect(typst.contains("Second"))
    }

    // MARK: - 8.5 Typst Code Blocks

    @Test("Typst fenced code block")
    func typstCodeBlock() async {
        let md = "```python\nprint('hello')\n```"
        let typst = await RhoeMarkdownKit.toTypst(md)
        #expect(typst.contains("```python"))
        #expect(typst.contains("print('hello')"))
    }

    // MARK: - 8.6 Typst Tables

    @Test("Typst table renders with #table")
    func typstTable() async {
        let md = "| A | B |\n|---|---|\n| 1 | 2 |"
        let typst = await RhoeMarkdownKit.toTypst(md)
        #expect(typst.contains("#table("))
        #expect(typst.contains("columns:"))
    }

    // MARK: - 8.7 Typst Block Quotes

    @Test("Typst block quote renders with #quote")
    func typstBlockQuote() async {
        let md = "> This is a quote."
        let result = await RhoeMarkdownKit.parse(md)
        let typst = RhoeMarkdownKit.renderTypst(result.document, configuration: .flat)
        #expect(typst.contains("#quote(block: true)"))
    }

    // MARK: - 8.8 Typst Preamble

    @Test("Typst preamble generated by default")
    func typstPreamble() async {
        let md = "# Hello\n\nWorld."
        let typst = await RhoeMarkdownKit.toTypst(md)
        #expect(typst.contains("#set page("))
        #expect(typst.contains("#set text("))
    }

    @Test("Typst fragment mode omits preamble")
    func typstFragmentMode() async {
        let config = RhoeMarkdownKit.TypstConfiguration(generatePreamble: false, astNearEmission: false)
        let result = await RhoeMarkdownKit.parse("# Hello\n\nWorld.")
        let typst = RhoeMarkdownKit.renderTypst(result.document, configuration: config)
        #expect(!typst.contains("#set page("))
        #expect(typst.contains("= Hello"))
    }

    // MARK: - 8.9 Typst Escaping

    @Test("Typst special characters escaped")
    func typstEscaping() async {
        let md = "Email: user@example.com and #hashtag"
        let typst = await RhoeMarkdownKit.toTypst(md)
        #expect(typst.contains("\\@"))
        #expect(typst.contains("\\#"))
    }

    // MARK: - 8.10 DOCX Output

    @Test("DOCX produces non-empty data")
    func docxProducesData() async {
        let md = "# Hello\n\n**World**."
        let data = await RhoeMarkdownKit.toDOCX(md)
        #expect(!data.isEmpty)
    }

    @Test("DOCX contains document.xml markers")
    func docxContainsXML() async {
        let md = "# Hello\n\nParagraph text."
        let data = await RhoeMarkdownKit.toDOCX(md)
        // The ZIP data should contain the document.xml content
        // We can verify by checking that the data is a valid ZIP (starts with PK)
        #expect(data.count > 100)
        if data.count >= 2 {
            #expect(data[0] == 0x50) // P
            #expect(data[1] == 0x4B) // K
        }
    }

    @Test("DOCX with heading styles")
    func docxHeadingStyles() async {
        let md = "# Main Title\n\n## Subtitle"
        let data = await RhoeMarkdownKit.toDOCX(md)
        // Verify the DOCX is valid (non-empty ZIP with PK header)
        #expect(data.count > 100)
    }

    @Test("DOCX with bold and italic")
    func docxFormatting() async {
        let md = "This is **bold** and *italic*."
        let data = await RhoeMarkdownKit.toDOCX(md)
        #expect(!data.isEmpty)
    }

    @Test("DOCX with table")
    func docxTable() async {
        let md = "| A | B |\n|---|---|\n| 1 | 2 |"
        let data = await RhoeMarkdownKit.toDOCX(md)
        #expect(!data.isEmpty)
    }

    @Test("DOCX with frontmatter title")
    func docxFrontmatter() async {
        let md = """
        ---
        title: My Document
        author: Thor Fuchs
        ---

        # Introduction

        Hello.
        """
        let data = await RhoeMarkdownKit.toDOCX(md)
        #expect(!data.isEmpty)
    }
}
